/**
 * Declare action types for reducers
 */
export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';

export const CREATE_CLIENT_REQUEST = 'CREATE_CLIENT_REQUEST';
export const CREATE_CLIENT_FAILURE = 'CREATE_CLIENT_FAILURE';
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS';

export const FETCH_TYPES_OF_IDENTITY_DOCUMENT_REQUEST = 'FETCH_TYPES_OF_IDENTITY_DOCUMENT_REQUEST';
export const FETCH_TYPES_OF_IDENTITY_DOCUMENT_FAILURE = 'FETCH_TYPES_OF_IDENTITY_DOCUMENT_FAILURE';
export const FETCH_TYPES_OF_IDENTITY_DOCUMENT_SUCCESS = 'FETCH_TYPES_OF_IDENTITY_DOCUMENT_SUCCESS';

export const FETCH_AREAS_REQUEST = 'FETCH_AREAS_REQUEST';
export const FETCH_AREAS_FAILURE = 'FETCH_AREAS_FAILURE';
export const FETCH_AREAS_SUCCESS = 'FETCH_AREAS_SUCCESS';